[package]
name = "text-translator-cli"
version = "0.1.0"
authors = ["janosimas <janosimas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-translator = { path = "../text-translator" }
clap = "2.33.3"